add_newline     = true
command_timeout = 1000
scan_timeout    = 80

[character]
error_symbol   = "[✗](bold red) "
success_symbol = "[➜](bold green) "

[cmd_duration]
format            = "took ⏲️ [$duration](bold yellow)"
min_time          = 5
show_milliseconds = true

[directory]
truncate_to_repo = true

[memory_usage]
disabled  = false
format    = "with $symbol [${ram}(${swap})]($style) "
threshold = -1

[status]
disabled = false

[sudo]
disabled = false

[username]
disabled    = false
format      = "[$user]($style) at "
show_always = true
style_root  = "red bold"
style_user  = "green bold"

[env_var]
symbol = '$'
